"""add column ProductModel.created_at and ProductModel.updated_at

Revision ID: 57e59206d6da
Revises: 69880a966de8
Create Date: 2026-03-24 10:27:51.558185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57e59206d6da'
down_revision: Union[str, Sequence[str], None] = '69880a966de8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('products', sa.Column('upddated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'upddated_at')
    op.drop_column('products', 'created_at')
    # ### end Alembic commands ###
