"""modify check

Revision ID: 69880a966de8
Revises: e939f0cb4d7b
Create Date: 2026-03-24 09:16:09.146274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69880a966de8'
down_revision: Union[str, Sequence[str], None] = 'e939f0cb4d7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_grade', 'reviews', type_='check')
    op.create_check_constraint('check_grade', 'reviews', 'grade >= 0 AND grade <= 5')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_grade', 'reviews', type_='check')
    op.create_check_constraint('check_grade', 'reviews', 'grade >= 1 AND grade <= 5')
    # ### end Alembic commands ###
