"""Add check

Revision ID: e939f0cb4d7b
Revises: e9aef610892a
Create Date: 2026-03-23 22:21:12.189312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e939f0cb4d7b'
down_revision: Union[str, Sequence[str], None] = 'e9aef610892a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('check_grade', "reviews", "grade >= 1 AND grade <= 5")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_grade', "reviews", type_='check')
    # ### end Alembic commands ###
